# PHP-Apache container
glpi:
  build: ./php
  ports:
    - "8090:80"
  links:
    - mysql:db
  volumes:
    - ./glpi/glpi:/var/www/html

# Database persistent data
mysqldata:
  image: ubuntu
  volumes:
    - /var/lib/mysql

# Database container
mysql:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=arcom1973
    - MYSQL_DATABASE=glpiatualizacao
  volumes_from:
    - mysqldata
  volumes:
    - ./database:/docker-entrypoint-initdb.d
